{% set version = "0.9.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-liftr
  version: {{ version|replace("-", "_") }}

source:
  fn: liftr_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/liftr_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/liftr/liftr_{{ version }}.tar.gz
  sha256: 7d84c03bfa98cc896192905ee2d9cf7c7f90e436080f7504661b38c2c240f12b

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-knitr
    - r-rmarkdown
    - r-rstudioapi
    - r-stringr
    - r-yaml
  run:
    - r-base
    - r-knitr
    - r-rmarkdown
    - r-rstudioapi
    - r-stringr
    - r-yaml

test:
  commands:
    - $R -e "library('liftr')"  # [not win]
    - "\"%R%\" -e \"library('liftr')\""  # [win]

about:
  home: https
  license: GPL-3
  summary: Persistent reproducible reporting by containerization of R Markdown documents.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
