{% set version = "0.9.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-liftr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/liftr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/liftr/liftr_{{ version }}.tar.gz
  sha256: 7d84c03bfa98cc896192905ee2d9cf7c7f90e436080f7504661b38c2c240f12b

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-knitr
    - r-rmarkdown
    - r-rstudioapi
    - r-stringr
    - r-yaml
  run:
    - r-base
    - r-knitr
    - r-rmarkdown
    - r-rstudioapi
    - r-stringr
    - r-yaml

test:
  commands:
    - $R -e "library('liftr')"           # [not win]
    - "\"%R%\" -e \"library('liftr')\""  # [win]

about:
  home: https://nanx.me/liftr/, https://github.com/nanxstats/liftr
  license: GPL-3.0-only
  summary: Persistent reproducible reporting by containerization of R Markdown documents.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
