travis:
  secure:
    BINSTAR_TOKEN: e5iY+ENfBFEZTAU2AxhBMJp4GFXQ9mHfv1zMERmxSyFVs2JklMXlJRItKYdmIAZ4vIcC7OpNWFbpFsgKW65G+Aka8VZ+crAP0KUomVLimlSvf+/jzxgCnSNdfCFoRs04vDBx7CNf4ykBNnVWLs9PuPCFtIDAwjyT2LAWm/IywQ0UP6gr9/1VlILkO6+fLk4Q1+/e6kE66GrLRWipR1lAe4RpV7HkKxtC7IcYqsPYuVJPxOARVmyYL8F688uLjUcPUg9o4rgR2YMNlUE5jQ68OJEgn/kXyMk/j1ByXmeJDs7rDFjfwmqLJ5TVp+8Hg/EizMwJQXBfFR5laIjk4x48NGkY7+TjSDVE6ZHEb9Hf9oSn9MLStuDnqx9IFdxN2WqTrknNBuFT/02A/OT/w0DqcFX/J3PEbNi7ll2sDMpohKQoV6Is36Ik0b7I3JOexXs7jb/bvttrt9+3o+PMqbLtUuPWR025UGOdpFEEoukilu5a9JSNeQKIrHi7ksquzps4FQghjpUL/w+MfG0OmibQCw40dnI50grVR0qfN24U1K+8+ykWraLtW45OCP2mLQRR1sqvYJVUZ2psuazcwMeEI0CeG0qvVs/1RLWyydO9DRqj4HzkR+OoY+pLJgnz+72B1no1Nd1Ky2LiI3XYXOdzMQj6Nos+nM31bVCKdEJWwNc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
