travis:
  secure:
    BINSTAR_TOKEN: vfkqqUWGDxY4jzzuyLWNE3Vm9UGOs38tgR4l0hoT0Rd0BebA/Mi1WvStfewUpiRMWNyNJ6VJcarahaiJjZLAt+pms1PgZBILzubVb3gUeJTEreQwJQ19FSdjn3+yRNNZ0WS0O77qFP8V3N8nukPfah4pZekMXBeAUitpvxQwm7CZ+ksng70RtFULJp+c7U0HG3OrUCfNCQTcnFA262RQtrLmysCMO0wlpfAX9mKkL/iZzYjyTmuO8bvs+6W6On8bF0rTVVPjnRoM/WnrGcobLMPSEvhJETWv162vWmyL+Nqy1iFJe91KhM7T5jN6+7LpOyc3ywsAf2h6gfI8Bv5eWNTF5fgJ/zZIyFnvuzsHj+fsDbKCqzx82rD6BR8o/OGGsT5WhulBdCaWpxkSSwe5DE/32+0l1qmacn0Zodn+bDI0Lh5AmmW+7dC0JrF3KHa0+L+uMK0xLkHSPjOxdFbLvELzx1KWZDacIc2XGUksExEm69lTK1jOairdIkyQuTlCvTD5ZEljrTMmT0UlaN9k9dlrL+i4yzzcb2hNg2bXCuCcmF6/G2wSEF1FuV2VYfvP2foxjEtrszPUc1TyZKtWlu8uNnOiEUxgH1xp/I8unkJgipI3gxpqwecJE8dILG6Y0YYAtbkwPn2CYUsd54q+RxLVMO7ox2xzyHqaQNOj618=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
