travis:
  secure:
    BINSTAR_TOKEN: O9COKvAsfqw/qp7APDMcbfjWAMOlieCATR2IJFGOz6l1KnVSTTWaszHbrYnoc3/coJGjuRXXfOSOUQ33s8OCdgZrppDsXf2AVlCINaRtWWOHaV7vPdfTihRki7ydARYf6x81Yw88YINMSdfdeHnvceP/NK47GSHGLYVEAXU3GQAk8FHeq/oC3cvJ1Kq1aEpJU+AQT90b+0U8XffgOH85I+4o5hgI1gKGTo8nkwXUjXCcgZMiGPUT45u9FNR02BFuC/LsCdPUUiB2A0hxGWin3V6fU7SYcvUWyRQ4a2gjfVmLjB8rnChwJkkJMskbMYjKK/hDd996A3dHWNn84CzWBlVcvLHEZdFnri57L+4uw132tWDFaCIstxvIuJ5gmFKG6nvjU5yNYTJY6Ox0dMlOyj0OgtDQ1XizCxf5YQ5FtaVFYsVax/IA/OhaROFfQH85oiWhAO1KMRFbLKvoPaN16Pd6hk4O5ICKr6x00gl+x+i8Y3PRdpB9kPK93PHXloHXldz0yWNgne5RIaEj0oElwRZV4dRZHUd6HcJM1ZhLYg9eYBbNJCa18ocjtoplTtRMCIdX95yiadk876po+TiKgALXyHUv722qt52H+JDp2MFBL6vRvkdcFkyRai6JIdU/yePE7zH6EfCAGrJ+GdPmHN/lE1SVRnOQjnPXi/LGqlU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
