travis:
  secure:
    BINSTAR_TOKEN: N3m4olvv3GTnzGCt3ATQheMeJKLmaxcUzPeBQxOWuA8/3QZy1oX6hclpySrpH2+usxNsgHz/tFE+C7wwQQbvg8ZDG9GAiy4IpGPVbeIUzELgw60gR72SrwwV8xKHPlBNQMe+AeIAIDZrSuowZICrNjUnuGeZ2VBxkxdp1VHf/Jy0uq719sNcVwkdTPk3RyjzOBV6Gp5dr6bnSEqLnS51PRjh0GdECtme6JxOmCxOzX+5DFie/ZhQmw8BijBNz4lTBQeqvXGp8hfH98dcRd9v5Rn2yJfMsOd/toDezIj7KX3EjeEhAxasiv0CxVExvVAUAxIMuwvC6w9jgHdAwPnoEGW5FG01iWobT8u4BJMRjDQTFdycrL5JDnKdG59gWtDFf9wwauf7Q6qTwCpNhzVKA8Jo9QMekBxfp+I4BNAGz+dwE1jYeV8xyEFqY8AxakHD4IaNzEyzE3pimzg1zVnfoDweyJZB3prriRneLoIDKa3pQlKEXOA+Y+Cn4Fc73EJuGurauntsRKtBrjQze0abN+8csLhDGhte/99CbBmnIzLrqrfF+rP8Sfl7JYd4kwv6v5EDULl9k+/csQxThtjs2QQhsNw681njgz361IwgMbQ2DbNjdlqcMh5UvnlVKs0QEKhTrxs0HzejcAkeFLCAxmEfah1qfScX7OO41UZKlGA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
