travis:
  secure:
    BINSTAR_TOKEN: EOOgZCHEryZR9pAodTtGAFzGu4tRuiE9MZ/jfsn+VnABquqdJ+J9+IhcDhD8TP92uzVv6xSBpt/gmznqjsEFwSrjKbAviX66ef42cW+5ggrBvXfGYXjohK2mWo39qt1FoweMyEsEYrd6JpxztOVGRd45r9Q1jtjpCaqJBLTqYQOWD2vgn4u+Pk08uJl3lERvtCKdcQ6N8BZ147xRnpXJvlWk5jS9KN5v2Ws1lm8ywEQI9Zl57rt9QoyJeTop1h3t0qgfXZCyCF5JShKok/FParU12nyxBpQnDp8WRJn5pXBvk9n83mlDpoc5ChkG2wVNKN8HHw4VcDOTV+MVezs+p1WZJqn8l/DhAMVnKfU09sjVU0mzj0823QOqs2ip6U5V3ofkL0xwbP59y5azf7U/LnV6T/lh4/PXS0gMnqHHC6aqTRZLb7sqZ3ZuBieBVVsmtXt2/esleKnLJzq6UW0wk/JzXsO2Or61Jbipusuii/se4RFbyFERG/7116DIvTVDiK61d6xn4X1Px+iWsrkoLHiz8awjRrwrX7FiOasGCuKdsi7QNO+zlVIaRfUFkyxfmtvNd6yv/Fr701t2dIwwiRcbmgRvUPbZseIpJejdvFpaG3MvLza/H1lOpp64Lu0R1JKwsNxt62X9EwWrxY6SNuK96GUt31HjoczDMh8Ji2M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
