appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: kKBDwL6II5yN7wF9fJDYO3Z6FFBcuVTGXbov2abeh905QlUgtnFjs7+OOvdi1io3NBE+KJnXfyfEnvmHyNH3BQ5paFHiAsyYZ4/GzQYOACNlNgKRCSMgA7vD444slJxUg6SNWotZbkxHRGX92CJGUn8mNK/AmKAasFpAZ/IlJjnGp68ctMR0K7/ifkc+HqMODTV0nrVJrg4CA0zSAsJ04fEbLrzpo0EvcnUchW241qM4qomoMH6bXiizpuU+Ki+w9qjh65t3ivdJsLZLm5VcuHyDNMeEDjVwwgqQID5OqMMnRKrVZiru1r1IG99hVgfFJ5Zeh3u4FjdVgzOrIfOm8FbSqGC4mx2LsSYU/Io+Zmilu6ai++bW2RSdymDn4Y1IRdc5IXdHc9bDg6Rx4miuefeK0LwPCS/IdH80gXa6Hd+FGRW6X7a8hAECVdNY1ObsAnyjXEZN7b0nilJJu/ogIh47nvRUfq6Y0OKpNHv5Gf4jW2DJMNjvsfjBuNoGsGegEyG3uwioPtHiQM0lbPCpzH4Zr/hpLbCMpet9ctGyUOAgWPFtJZusEx0LZUrRgKP8jlE1n+KcR1luTKdOvf0zTKG3Q7nh2NAFL9RheKFEekAcj7EFFRIi7jrapgBCuTcdu1tOlT/FwIixt1cxae7VPCHoI17ey2bXqB/HpvPLLMw=}
bot:
  automerge: true
